Clear some validation warnings, fixed validation error of google-closure jQuery.scrollSpeed.js:92: ERROR - Parse error. missing name after . operator     jQuery.easing.default = function (x,t,b,c,d) {                   ^